"""create auto generate likes table

Revision ID: 05ee9d5c9946
Revises: ef70e60b12da
Create Date: 2023-07-27 21:50:18.055444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ee9d5c9946'
down_revision = 'ef70e60b12da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.drop_constraint('ingredient_recipe_fk', 'ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'ingredients', 'recipes', ['recipe_id'], ['id'])
    op.drop_constraint('nutrition_recipe_fk', 'nutritions', type_='foreignkey')
    op.create_foreign_key(None, 'nutritions', 'recipes', ['recipe_id'], ['id'])
    op.drop_constraint('step_recipe_fk', 'steps', type_='foreignkey')
    op.create_foreign_key(None, 'steps', 'recipes', ['recipe_id'], ['id'])
    op.drop_constraint('tag_recipe_fk', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tag_recipe_fk', 'tags', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.create_foreign_key('step_recipe_fk', 'steps', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'nutritions', type_='foreignkey')
    op.create_foreign_key('nutrition_recipe_fk', 'nutritions', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.create_foreign_key('ingredient_recipe_fk', 'ingredients', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_table('likes')
    # ### end Alembic commands ###
